apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-runner-token
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: controller-manager
    creationPolicy: Owner
  data:
  - secretKey: github_token
    remoteRef:
      key: secret/guitartortona/github
      property: runner_token
