apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-runner-token
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: controller-manager
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: secret/guitartortona/github
        property: token
