apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guitartortona-api-production
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: guitar-deployments
spec:
  project: default
  
  source:
    repoURL: https://github.com/mmzitarosa/guitartortona-api-deploy.git
    targetRevision: main  # Branch main
    path: environments/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  syncPolicy:
    # Production: SYNC MANUALE per sicurezza
    # Decommenta per abilitare auto-sync:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Ignora differenze repliche (gestite da HPA)
