---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup-pvc
  namespace: databases
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
  namespace: databases
  labels:
    app: mariadb-backup
spec:
  schedule: "0 2 * * *"  # Every day at 2 AM
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mariadb-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: mariadb:11
            env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root
                  key: password
            command:
            - /bin/sh
            - -c
            - |
              set -e
              DATE=$(date +%Y%m%d-%H%M%S)
              BACKUP_FILE="/backup/backup-$DATE.sql.gz"
              
              echo "Starting backup at $(date)"
              
              # Perform backup
              mariadb-dump -h mariadb.databases.svc.cluster.local \
                -u root -p${MARIADB_ROOT_PASSWORD} \
                --all-databases \
                --single-transaction \
                --quick \
                --lock-tables=false \
                --routines \
                --events \
                --triggers \
                | gzip > "$BACKUP_FILE"
              
              echo "Backup completed: $BACKUP_FILE ($(du -h $BACKUP_FILE | cut -f1))"
              
              # Keep only last 7 backups
              cd /backup
              ls -t backup-*.sql.gz | tail -n +8 | xargs -r rm -f
              
              echo "Cleanup completed. Current backups:"
              ls -lh backup-*.sql.gz
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mariadb-backup-pvc
