apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-root-credentials
  namespace: databases
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mariadb-root
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: secret/guitartortona/mariadb
      property: root_password
