apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: databases
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  clusterIP: None  # Headless service per StatefulSet
  selector:
    app: mariadb
