apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  ports:
  - port: 8200
    targetPort: 8200
    name: api
    protocol: TCP
  - port: 8201
    targetPort: 8201
    name: cluster
    protocol: TCP
  selector:
    app: vault
  type: ClusterIP
