apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.20.4
          command:
            - vault
            - server
            - -config=/vault/config/vault.hcl
          ports:
            - containerPort: 8200
              name: api
            - containerPort: 8201
              name: cluster
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: SKIP_SETCAP
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /vault/data
            - name: config
              mountPath: /vault/config
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        # AUTO-UNSEAL SIDECAR (semplificato)
        - name: vault-unsealer
          image: hashicorp/vault:1.20.4
          command:
            - /bin/sh
            - -c
            - |
              sleep 20
              while true; do
                if vault status 2>&1 | grep -q "Sealed.*true"; then
                  vault operator unseal "$VAULT_UNSEAL_KEY"
                fi
                sleep 15
              done
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_UNSEAL_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: unseal-key
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

      volumes:
        - name: config
          configMap:
            name: vault-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: microk8s-hostpath
        resources:
          requests:
            storage: 5Gi